spring.application.name=bookverse-api


# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/bookverse2
spring.datasource.username=root
spring.datasource.password=Anas@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL Console me dikhane ke liye
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
